service: wordle-solver

frameworkVersion: '3'

plugins:
  - serverless-rust

custom:
  rust:
    dockerTag: '0.4.0-rust-1.58.1'
    dockerImage: 'rustserverless/lambda-rust'
    cargoFlags: '--features lambda'

provider:
  name: aws
  region: eu-west-2
  stage: dev
  memorySize: 128
  timeout: 5
  tracing:
    lambda: true
  iam:
    role:
      managedPolicies:
        - 'arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess'

package:
  individually: true
  patterns:
    - '!./**'

functions:
  GenerateGuesses:
    handler: wordle-solver.generate_guesses
    runtime: rust
    events:
      - http:
          path: /generate-guesses
          method: POST
          cors: true
    environment:
      RUST_LOG: info

resources:
  extensions:
    GenerateGuessesLogGroup:
      Properties:
        RetentionInDays: '60'